cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'bash'
brew 'bash-completion'
brew 'coreutils'
brew 'git'
brew 'grc'
brew 'htop'
brew 'imagemagick'
brew 'jp2a'
brew 'jpeg'
brew 'jq'
brew 'libgit2'
brew 'libidn2'
brew 'libpng'
brew 'libunistring'
brew 'node'
brew 'openssl'
brew 'pkg-config'
brew 'postgresql'
brew 'python'
brew 'rbenv'
brew 'readline'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'sqlite'
brew 'unrar'
brew 'wget'
brew 'xz'
brew 'youtube-dl'
brew 'zsh'
brew 'zsh-completions'

cask '1password'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'transmission'
cask 'vlc'
